### PR TITLE
Use multiple providers to address rate-limiting

### LINKED ISSUE #22: The PM site is being rate-limited by alchemy via publicProvider
Screen Shot 2022-10-21 at 4 01 55 PM

See discussion in songcamp discord: https://discord.com/channels/824116816363520020/1013905059765039236/1033081118259425401

### PR DESCRIPTION
**Pull request by neatonk**
- I've added two providers which take priority over the `publicProvider`.
- I've not added the `alchemyProvider` since this is what the publicProvider uses internally for mainnet ethereum.
- I've configured a `jsonRpcProvider` to use the public Ethereum endpoint provided by [ankr](https://www.ankr.com/rpc/).

Fixes #22

### CODE REVIEW

**Comment by 0xTranqui** [comment]
hey thanks for making this commit. I actually just pushed a fix just now before noticing ur commit

**Comment by 0xTranqui** [comment]
@neatonk if u want to re submit the pr around the provider architecture I added please do and ill merge!

**Review by 0xTranqui — APPROVED** [review]

**Comment by 0xTranqui** [comment]
@neatonk sorry for the confusion, actually re opened ur PR cuz the change I thought I made hadnt fixed the issue like yours did! just re merged

**Comment by neatonk** [comment]
Hey, thanks for merging this. No worries about the confusion.

**Pull request merged**
